name: Dev Deployment

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - '**'   # allow PRs from any branch

jobs:
  deploy-dev:
    if: |
      github.ref != 'refs/heads/main' &&
      startsWith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Dev
        run: echo "Deploying feature branch to Dev environment....feature/branch.."
